 
# @endpoint = https://600np39uw1.execute-api.us-east-1.amazonaws.com/prod/
@endpoint =https://y9cqbjv73f.execute-api.us-east-1.amazonaws.com/prod/

 GET {{endpoint}}/hello
###



GET {{endpoint}}/spaces
###


GET {{endpoint}}/spaces?sp-Id=c17c1b47-56e3-4d17-a609-40f6ec658a6e
###

POST  {{endpoint}}/spaces/
Content-Type: application/json

{
    "name": "test-spacedd",
    "location": "test-space-locationdd"
}

###